dist: xenial
sudo: required
branches:
  only:
  - master
  - "/^release-.*$/"
before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script:
  - cd function/
  - |
   if [ "${TRAVIS_BRANCH}" == "master" ]; then
     export TAG="latest"
   else
     export TAG=${TRAVIS_BRANCH}
   fi
  - |
     docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t tika-convert-to-text:$TAG --push .
     docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t tika-convert-to-text:server-$TAG . -f Dockerfile.server --push .
     docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t tika-convert-to-text:ui-$TAG ../ui/ -f ../ui/Dockerfile --push .
     docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t tika-convert-to-text:openfaas-$TAG . -f Dockerfile.faas --push .
after_script:
  - docker images
notifications:
  email: true
  on_success: always
  on_failure: change
after_success:
  - echo "All done!"
