services:
  - docker
language: python
install: true
git:
  depth: 3
  submodules: true
branches:
  only:
  - master
  - "/^release-.*$/"
before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script:
  - cd function/
  - |
    if [ "$TRAVIS_BRANCH" != "master" ]; then
     docker build -t saidsef/tika-convert-to-text:${TRAVIS_BRANCH} .;
    fi
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
     docker build -t saidsef/tika-convert-to-text:latest .;
    fi
  - |
    if [ "$TRAVIS_BRANCH" != "master" ]; then
     docker build -t saidsef/tika-convert-to-text:openfaas-${TRAVIS_BRANCH} . -f Dockerfile.faas;
    fi
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
     docker build -t saidsef/tika-convert-to-text:openfaas . -f Dockerfile.faas;
    fi
  - docker push saidsef/tika-convert-to-text
notifications:
  email: true
  on_success: always
  on_failure: change
after_success:
  - echo "All done!"
