services:
  - docker
language: python
install: true
git:
  depth: 3
  submodules: true
branches:
  only:
  - master
  - "/^release-.*$/"
before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script:
  - cd function/
  - export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-TRAVIS_BRANCH}
  - |
    if [ "${BRANCH}" != "master" ]; then
     docker build -t saidsef/tika-convert-to-text:${BRANCH} .;
     docker build -t saidsef/tika-convert-to-text:ui-${BRANCH} . -f ./ui/Dockerfile;
    fi

    if [ "${BRANCH}" == "master" ]; then
     docker build -t saidsef/tika-convert-to-text:latest .;
     docker build -t saidsef/tika-convert-to-text:ui-latest . -f ./ui/Dockerfile;
    fi

  - |
    if [ "${BRANCH}" != "master" ]; then
     docker build -t saidsef/tika-convert-to-text:openfaas-${BRANCH} . -f Dockerfile.faas;
    fi

    if [ "${BRANCH}" == "master" ]; then
     docker build -t saidsef/tika-convert-to-text:openfaas . -f Dockerfile.faas;
    fi
  - |
    docker push saidsef/tika-convert-to-text || true
    docker push saidsef/tika-convert-to-text-ui || true
notifications:
  email: true
  on_success: always
  on_failure: change
after_success:
  - echo "All done!"
