dist: xenial
sudo: required
branches:
  only:
  - master
  - /.*/
before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
script:
  - cd function/
  - |
   if [ $TRAVIS_BRANCH == "master" ]; then
     export TAG="latest"
   else
     export TAG=$TRAVIS_BRANCH
   fi
  - docker build -t saidsef/tika-convert-to-text:$TAG .
  - docker build -t saidsef/tika-convert-to-text:server-$TAG -f Dockerfile.server .
  - cd ../ui/ && docker build -t saidsef/tika-convert-to-text:ui-$TAG -f Dockerfile .
  - docker push saidsef/tika-convert-to-text
after_script:
  - docker images
notifications:
  email: true
after_success:
  - echo "All done!"
