project: default
source:
  repoURL: 'https://github.com/saidsef/faas-convert-to-text.git'
  path: deployment/k8s
  targetRevision: master
  directory:
    jsonnet:
      extVars:
        - name: HOST
          value: $(HOST)
destination:
  server: 'https://kubernetes.default.svc'
  namespace: web
syncPolicy:
  automated:
    prune: true
    selfHeal: true