---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: web
  labels:
    name: tika
    app: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7070"
      labels:
        app: tika
    spec:
      containers:
      - name: tika
        image: saidsef/faas-tika:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: web
  labels:
    app: tika
    tier: frontend
spec:
  type: NodePort
  selector:
    app: tika
  ports:
  - protocol: TCP
    port: 7070
    targetPort: 7070
    name: web
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tika
  namespace: web
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    ingress.kubernetes.io/send-timeout: "3600"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      server_tokens off;
spec:
  rules:
  - host: tika.saidsef.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: tika
          servicePort: 7070
