---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: web
  labels:
    app: ui
    tier: frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: NodePort
  selector:
    app: ui
  ports:
  # - protocol: TCP
  #   port: 7070
  #   targetPort: 7070
  #   name: web
  - protocol: TCP
    port: 7071
    targetPort: 7071
    name: server
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: ui
