---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: web
  labels:
    app: ui
    tier: frontend
  annotations:
    prometheus.io/scrape: "true"
    filter.by.port.name: "true"
spec:
  type: NodePort
  selector:
    app: ui
  ports:
  # - name: web
  #   protocol: TCP
  #   port: 7070
  #   targetPort: 7070
  - name: server
    protocol: TCP
    port: 7071
    targetPort: 7071
  - name: ui
    protocol: TCP
    port: 8080
    targetPort: 8080
